# Generated by c_compiler.py  (source: program.c)
# Compatible with rv64im_assembler.py

    .text

    .global main
main:
    # ── prologue ─────────────────────────────
    ADDI     sp, sp, -32
    SD       ra, 24(sp)
    SD       s0, 16(sp)
    ADDI     s0, sp, 32
    # ── body ────────────────────────────────
    SW       zero, -8(s0)
    LI       t0, 0
    SW       t0, -16(s0)
    # for (line 7)
    ADDI     t5, s0, -8
    ADDI     sp, sp, -8
    SD       t5, 0(sp)
    LI       a0, 0
    LD       t5, 0(sp)
    ADDI     sp, sp, 8
    SD       a0, 0(t5)
.Lfor_cond0:
    LW       t1, -8(s0)
    ADDI     sp, sp, -8
    SD       t1, 0(sp)
    LI       t0, 100
    LD       t1, 0(sp)
    ADDI     sp, sp, 8
    SLT      t0, t0, t1
    XORI     t0, t0, 1
    BEQ      t0, zero, .Lfor_end2
    ADDI     t5, s0, -16
    ADDI     sp, sp, -8
    SD       t5, 0(sp)
    LW       a0, -16(s0)
    ADDI     sp, sp, -8
    SD       a0, 0(sp)
    LW       t0, -8(s0)
    LD       a0, 0(sp)
    ADDI     sp, sp, 8
    ADD      a0, a0, t0
    LD       t5, 0(sp)
    ADDI     sp, sp, 8
    SD       a0, 0(t5)
.Lfor_step1:
    ADDI     t0, s0, -8
    LD       t0, 0(t0)
    ADDI     t1, t0, 1
    SD       t1, 0(t0)
    JAL      zero, .Lfor_cond0
.Lfor_end2:
    LI       a0, 0
    JAL      zero, .Lmain_end
.Lmain_end:
    # ── epilogue ────────────────────────────
    LD       ra, 24(sp)
    LD       s0, 16(sp)
    ADDI     sp, sp, 32
    JALR     zero, ra, 0


    .data

